services:
  - type: web
    name: bookshelf-app
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn BookShelf.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: DEBUG
        value: False
      - key: SECRET_KEY
        generateValue: true
      - key: OPENAI_API_KEY
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: bookshelf-db
          property: connectionString
    autoDeploy: true

databases:
  - name: bookshelf-db
    databaseName: bookshelf
    user: bookshelf

